# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d703845863b35ec3013f2f21567960cd1065a3c15519706a49832a8a6975ce3a210473fa73c6378caab729d6886bbb58e01671b6db2023c078ac1a5459826769

test:
  secret_key_base: 6b208cd3d8c672991b9c40548204430b772ca148906f6ab5ff83bb2321839fa416025aa18a79a7149ab962f26c69f3d849765f615ee6de44dde9a2c6627b14f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
